### ISSUE TITLE
typeの定義を話しの最初にいれていただきたい

### ISSUE THREAD

**Issue by mahya8585** [mike-neck/javajo-gradle#15]
https://github.com/mike-neck/javajo-gradle/blob/master/document/1-java/1-init.adoc

にていきなちtypeの説明に入っているように見える（少なくとも文章上は）のですが、できれば使うコマンドなどについては先に役割（定義）をざっくり教示いただいてから実コマンドの実打に移れるような流れだとより理解しやすくなるかな、と思いました。

この章に限らず、コマンド実行前（場合によってはコマンド実行後でももちろんOKです！）に使うコマンドの役割（定義）を教示いただいてから作業できるとより良くなるかと思いました！

＊口頭での対応になるのかもしれないので、的外れなこと言っていたらするーしてください！

**Comment by mike-neck** [comment]
プルリクの #16 見てみて！

**Comment by mahya8585** [comment]
確認しました！ありがとうございます！
