### ISSUE TITLE
[質問] Build Init Plugin のインストールについて

### ISSUE THREAD

**Issue by mahya8585** [mike-neck/javajo-gradle#17]
大変無知で申し訳ないんですが・・・

[１章](https://github.com/mike-neck/javajo-gradle/blob/master/document/1-java/1-init.adoc) で使われているBuild Init Plugin は最初から(Gradleをインストールした時から）使えるプラグインなのでしょうか・・・？
それとも別になにか設定が必要なものなのでしょうか・・・？

（いきなりコマンド打ったら使える状態だったのでどこで設定されているのかしら・・・と不思議に思ってしまった次第です・・・初心者な感じですみません・・・

**Comment by mike-neck** [comment]
最初から使えますよー

https://docs.gradle.org/current/userguide/build_init_plugin.html

> The Build Init plugin is an automatically applied plugin, which means you do not need to apply it explicitly. To use the plugin, simply execute the task named init where you would like to create the Gradle build. There is no need to create a “stub” build.gradle file in order to apply the plugin.

#### 意訳

`init` プラグインは自動的に適用されるプラグインです。つまり明示的に適用すると宣言しなくて良いのです。このプラグインを使うには、Gradleプロジェクトを作りたいディレクトリーで `init` タスクを実行すればよいだけです。これを使うには、事前に `build.gradle` ファイルを用意する必要はありません。

説明があったほうが丁寧ですかね…？？？？

ただ、Gradleそのものでは何もできなくて、プラグインを適用して初めて様々なタスクを実行できるようになる旨の説明を 2-simple.adoc で説明しているので、うーん、まあ、最初の資料(今はない！)にも簡単に説明しておいたほうが良い気がしなくもない気がする…

**Comment by mahya8585** [comment]
英語音痴ですみません・・・！リンク先のページにしっかり記載されてましたね＞＜！
今まさに2-simple.doc やってるところだったので今となってはふむふむと話しがつながりはじめているのですが、
もしよろしければ1-init.adocを始める時に、あとでちゃんと説明するよ的なことを口頭で挟んでいただくか資料に一文潜ませていただければよいかと思います！

**Comment by mike-neck** [comment]
はい！

**Comment by mahya8585** [comment]
ありがとうございます！クローズします！

**Comment by mike-neck** [comment]
あー、資料に一応しれっと書いておくのでクローズしないでぇ〜(´；ω；｀)

**Comment by mike-neck** [comment]
下記のドキュメントができたらクローズする
- Gradleの概要(Gradle単体では何もできない)
- 1-init.adocに上の引用と意訳をメモとして記述する

**Comment by mahya8585** [comment]
失礼しましたっ（´>人<｀）

**Comment by mike-neck** [comment]
#19 で半分対応した

**Comment by mike-neck** [comment]
#33 でもう片方の対応おわり
