### ISSUE TITLE
[確認] gradle tasks の見方

### ISSUE THREAD

**Issue by mahya8585** [mike-neck/javajo-gradle#18]
(簡単なJavaのサンプルプロジェクト)[https://github.com/mike-neck/javajo-gradle/blob/master/document/1-java/2-simple.adoc] 内でgradle tasksを使ったタスクの情報確認作業がありますが、

> Javaに関するタスクが何も表示されないことを確認してください。

上記作業の場合に確認するべき場所は「Build Setup tasks」欄であってますでしょうか・・・？

**Comment by mike-neck** [comment]
これは全部ですねー

Build Setup tasksもHelp tasksも両方ですね。

ここは口頭でも説明します(覚えてたら……)がBuild Setup tasksの各タスクのdescriptionにもHelp tasksの各タスクのdescriptionにもJavaコンパイルに関する記述がないことを確認してもらう作業になります。

まあ、文章にも書いてあったほうが丁寧ですかね？

**Comment by mahya8585** [comment]
当日口頭説明あるのであれば大丈夫です！！
（今はドキュメントだけで作業していたのでちょっぴり不安になったまでです！）

**Comment by mike-neck** [comment]
(お、覚えてたら…)…

**Comment by mahya8585** [comment]
(他に不安になる人がいなければ問題ないので....
