### ISSUE TITLE
[感想] 2-simple.adoc 演習6

### ISSUE THREAD

**Issue by mahya8585** [mike-neck/javajo-gradle#24]
他の演習に比べて記述例や単語の説明(testclassesとtestの違いとかtestCompileの追加場所など）が少なめな感じがし、ドキュメントのみで作業する場合は各タスクの意味や書き方を調べながら進める必要がありました。
当日みんなが悩んでしまうようであれば口頭で書き方のヒントなどをいただけると嬉しいかもです・・・！
（レベルアップ演習としてわざとなのかもしれません。その場合はこの感想無視してOkです！

**Comment by mahya8585** [comment]
今思えばここがはまりポイントだっただけかもしれません><

```
groupId - junit
artifactId - junit
version - 4.12
```

group , name, version と頭の中でひも付きが弱かっただけ・・・

**Comment by mike-neck** [comment]
#34 にて詳細なヒントつけた
