### ISSUE TITLE
[感想]4-fail.adoc 演習2

### ISSUE THREAD

**Issue by mahya8585** [mike-neck/javajo-gradle#26]
だいぶどハマりしました・・・・

あととりあえずはall greenになるようになったものの、これが意図した正解なのかはちょっとわかりません・・・・

（Java女子部、Java8に弱い人が多い入門者な感じなので本ソース改修は結構レベル高いかも・・・

**Comment by mike-neck** [comment]
ここは、interfaceのjavadoc読みながら、目の前で直していこうと思っているので(javadocに`null`の場合は、`Nothing`を返すことというのを見せながら)、そんなに気にされなくてもよいですよ。

**Comment by mike-neck** [comment]
当日説明する
