### ISSUE TITLE
ところどころmonospaceになっていない

### ISSUE THREAD

**Issue by mike-neck** [mike-neck/javajo-gradle#4]
`の前後に半角ブランクを入れ忘れてて、monospaceになっていない箇所がある

**Comment by ihcomega56** [comment]
[タスクの種類](https://github.com/mike-neck/javajo-gradle/blob/master/document/3-copy/1-pure-copy.adoc#gradleのタスクの種類)の箇条書きひとつめ、Javadocのところはシングルクオートになってます！

**Comment by mike-neck** [comment]
#23 で対応
