### ISSUE TITLE
transitive dependencyのご説明おねがいしたい

### ISSUE THREAD

**Issue by ihcomega56** [mike-neck/javajo-gradle#6]
2-init.adocの[3. groovy library type](https://github.com/mike-neck/javajo-gradle/blob/master/document/1-java/2-init.adoc#3-groovy-library-type)あたり
括弧書きですが、この手の余談はついつい気になってしまうので簡単におねがいできると嬉しいです(当日口頭補足でよいとおもいます)。

**Comment by mike-neck** [comment]
飽きない程度の説明入れますね

なお、訳語としては「推移的依存性」となります。

ライブラリーAが他のライブラリー(B-1/C-1)に依存している時に、プロジェクトとしてはA/B-1/C-1に依存が発生することを意味します。この場合、プロジェクトはB-1/C-1も依存ライブラリーとして解決しておかないと動作が保証できなくなります(特にテストなどで)。

この辺りは口頭だと説明しづらいので、図を使ったほうが良さそうですね。

**Comment by ihcomega56** [comment]
ありがとうございます！
時間足りそうなら、でOKかと存じます。よろしくお願いいたします。
