### ISSUE TITLE
設定(Convention)と規約(Configuration)の違い、ご説明おねがいしたい

### ISSUE THREAD

**Issue by ihcomega56** [mike-neck/javajo-gradle#7]
[標準的なJavaプロジェクトのプロジェクト構成](https://github.com/mike-neck/javajo-gradle/blob/master/document/1-java/1-normal-project.adoc#標準的なjavaプロジェクトのプロジェクト構成)あたり
設定(Convention)と規約(Configuration)の違い、簡単に口頭でご説明いただきたいです。

**Comment by mike-neck** [comment]
このドキュメント自体は削除してしまったのですが、Ant(とにかく設定)とMaven(規約もしくはツールの決まりに合わせろ)のスタンスの違い(Gradleは後者の考え方を継承している)も含めて、他のビルドツールとの比較として説明する予定です。

**Comment by mahya8585** [comment]
運営staffの中にもいたのですが、そもそもMavenしか使ったことない(Antしかつかったことない）、もしくはMavenは使ったことあるけど、すでに現場で作られたものがあるのをrunしたことしかない、みたいな今回のターゲットにギリギリ食らいついている勢が参加している可能性があります。
当日の参加者の雰囲気をみて、そもそもビルドツールよくわかってなさそうな人が多そうでしたらビルドツールの簡単な説明も挟んでいただけるとうれしいです。
（大丈夫そうな参加者が多そうでしたらすっとばしてよいです）

**Comment by mike-neck** [comment]
Gradle全般に関するドキュメントをまだ作ってないんで、今後頑張って作る予定です……

**Comment by mahya8585** [comment]
恐れ入ります・・・

**Comment by mike-neck** [comment]
#32 で対応
