### ISSUE TITLE
進め方のスタンスを知りたい(決めたい)

### ISSUE THREAD

**Issue by ihcomega56** [mike-neck/javajo-gradle#8]
難しいやつもありますが、進め方はどういうのを想定されてますか？
- 基本的なところを重点的に皆が理解するのを待ちながら進める(難しいところは時間があればやるか、宿題にする)
- おいてけぼりのひとがいても全部やるつもりで進める  
  etc...  

進行の参考にさせていただきます。

**Comment by mike-neck** [comment]
#5 とかぶるところもありますが、参加者がおいてきぼりを喰らうのは避けたいと思っています。
- 基本的なレベルの演習を通じて理解してもらう
- 難しい演習は下記のいずれか
  - 時間が余っている
  - 余力があればやる
  - 家帰ってからやってもらう

というスタンスを想定しています。

**Comment by ihcomega56** [comment]
承知です。頭に入れておきます。
スタッフもサポートに回れるように尽力します…！

**Comment by mike-neck** [comment]
よろしくお願いします(本当は事前に打ち合わせできるのがベストですけどね…)
